#!/bin/bash
set -uo pipefail

start() {
	importLogin
	waitingForListOfSystemToEnsureSystemIsRunning
	echo "Starting adding appTokens process..."
	#  loginUsingAppToken
	loginUsingIdpLogin
	addAppTokenToUsers "141414" "coraUser:15697099230192"
	logoutFromCora
}

importLogin(){
	source "$(dirname "$0")/login.sh"
}

waitingForListOfSystemToEnsureSystemIsRunning(){
 	echo "Waiting for application to start ..."
 	until curl -s --fail "${RUNNING_URL}" > /dev/null 2>&1; do
		sleep 5
	done

	echo "Application is ready. Running add appTokens script..."
}

addAppTokenToUsers() {
	for userId in "$@"; do
		echo "Adding appToken to user: ${userId}"
        addAppTokenToUser "${RECORD_URL}/user/$userId"
	done
}

addAppTokenToUser() {
	local url="$1"
	local readRecord=$(readData $url)
	local updateLink=$(getActionLinkFromDataRecord "$readRecord" "update")
 	local userNoActionLinks=$(getUserPartWithoutActionLinksFromRecord "$readRecord")
 	
 	local userWithNewTokenNote=$(addTokenNoteToUser "$userNoActionLinks" \
 		"Autogenerated token added and used as example user. WARNING! This token is publicly known! ")

	local updateAnswer=$(sendDataToServer "${updateLink}" "${userWithNewTokenNote}")
	local token=$(extractTokenFromUpdateAnswer "$updateAnswer")
	
	local createdExampleUser=$(createExampleUser "$userNoActionLinks" "$token")
}

readData(){
	 local url="$1"
	 echo $(curl -s -X GET -k -H "authToken: ${AUTH_TOKEN}" \
    	-H "Accept: application/vnd.cora.record+xml" "$url")
}

getActionLinkFromDataRecord(){
	local record="$1"
	local action="$2"
	echo $(echo "$record" | xmllint --xpath '//record/actionLinks/'"$action" - 2>/dev/null)
}

getUserPartWithoutActionLinksFromRecord(){
	local readRecord="$1"	
	local user=$(echo "$readRecord" | xmllint --xpath '//record/data/user' - 2>/dev/null)
	local userNoActionLinks=$(printf '%s\n' "$user" \
    	| xmlstarlet ed --omit-decl -d "//actionLinks" 2>/dev/null)
	echo "$userNoActionLinks"
}

addTokenNoteToUser(){
	local user="$1"
	local note="$2"
  
	local existingRepeatIds=$(xmlstarlet sel -t -v "//appTokens/appToken/@repeatId" -n <<< "$user")
	local repeatIdMax=$(echo "$existingRepeatIds" | awk '/^[0-9]+$/ {if($1>m)m=$1} END{print m+1}')
	local newRepeatId=${repeatIdMax:-1}
  
	local userWithAddedAppTokenNote=$(xmlstarlet ed --omit-decl \
		-s "/user[not(appTokens)]" -t elem -n appTokens -v "" \
		-s "/user/appTokens" -t elem -n appToken -v "" \
		-i "/user/appTokens/appToken[last()]" -t attr -n repeatId -v "$newRepeatId" \
		-s "/user/appTokens/appToken[last()]" -t elem -n appTokenNote -v "$note" \
		<<< "$user")
	echo $userWithAddedAppTokenNote
}

sendDataToServer() {
	local updateLink="$1"
	local data="$2"

	local url=$(echo "$updateLink" | xmllint --xpath 'string(//url)' - 2>/dev/null)
	local method=$(echo "$updateLink" | xmllint --xpath 'string(//requestMethod)' - 2>/dev/null)
	local contentType=$(echo "$updateLink" | xmllint --xpath 'string(//contentType)' - 2>/dev/null)
	local accept=$(echo "$updateLink" | xmllint --xpath 'string(//accept)' - 2>/dev/null)

	local updateAnswer=$(curl -s -X "$method" -k \
		-H "authToken: ${AUTH_TOKEN}" -H "Content-Type: ${contentType}" -H "Accept: ${accept}" \
		--data-binary '<?xml version="1.0" encoding="UTF-8"?>'"$data" "$url")
    echo "$updateAnswer"
}

extractTokenFromUpdateAnswer(){
	local updateAnswer="$1"
	local token=$(echo "$updateAnswer" | \
		xmllint --xpath 'string(/record/data/user/appTokens/appToken[last()]/appTokenClearText)' - )
	echo "$token"
}

createExampleUser(){
	local userData="$1"
	local appToken="$2"
	local url="${RECORD_URL}/recordType/exampleUser"
	local readRecord=$(readData "$url")
	local createLink=$(getActionLinkFromDataRecord "$readRecord" create)
	
	local userFirstname=$(echo "$userData" | xmllint --xpath 'string(/user/userFirstname)' - )
	local userLastname=$(echo "$userData" | xmllint --xpath 'string(/user/userLastname)' - )
 	local name="$userFirstname $userLastname"
	local userId=$(echo "$userData" | xmllint --xpath 'string(/user/recordInfo/id)' - )
	local text="Apptoken, $userId"
	local type="appTokenLogin"
	local loginId=$(echo "$userData" | xmllint --xpath 'string(/user/loginId)' - )
	
	local exampleUser=$(cat <<-EOF
	<exampleUser>
	  <recordInfo>
	    <validationType>
	      <linkedRecordType>validationType</linkedRecordType>
	      <linkedRecordId>exampleUser</linkedRecordId>
	    </validationType>
	    <dataDivider>
	      <linkedRecordType>system</linkedRecordType>
	      <linkedRecordId>coraData</linkedRecordId>
	    </dataDivider>
	  </recordInfo>
	  <name>${name}</name>
	  <text>${text}</text>
	  <type>${type}</type>
	  <loginId>${loginId}</loginId>
	  <apptoken>${appToken}</apptoken>
	</exampleUser>
EOF
	)
	local createAnswer=$(sendDataToServer "${createLink}" "${exampleUser}")
	echo "$createAnswer"
}

start