#!/bin/bash
set -uo pipefail

addAppTokenAndCreateExampleUsers() {
	importDependencies
	local note="Autogenerated token added and used as example user. WARNING! This token is publicly known!"
	for userId in "$@"; do
		echo "Adding appToken to user: ${userId}"
        local updateAnswer=$(addAndStoreAppTokenToUser "${RECORD_URL}user/$userId" "$note")
		createExampleUserFromUserAddAppTokenAnswer "$updateAnswer"
	done
}

addAppTokenToUser() {
	importDependencies
	local userId="$1"
	local note="$2"
    local updateAnswer=$(addAndStoreAppTokenToUser "${RECORD_URL}user/$userId" "$note")
    local token=$(extractTokenFromUpdateAnswer "$updateAnswer")
    echo "${token}"
}

removeAppTokensAndPasswordFromUserRecord(){
	local readRecord="$1"
	local updateLink=$(getActionLinkFromDataRecord "$readRecord" "update")
 	local userNoActionLinks=$(getUserPartWithoutActionLinksFromRecord "$readRecord")
 	local userWithoutAppTokens=$(removeAppTokensFromUser "$userNoActionLinks")
 	local userWithoutAppTokensOrPassword=$(removePasswordFromUser "$userWithoutAppTokens")
	if [[ "$userNoActionLinks" != "$userWithoutAppTokensOrPassword" ]]; then
		local updateAnswer=$(sendDataToServer "${AUTH_TOKEN}" "${updateLink}" "${userWithoutAppTokensOrPassword}")
		echo "$updateAnswer"
	fi
}

importDependencies(){
	SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
	source "$SCRIPT_DIR/../dataFromAndToServer.sh"
}

addAndStoreAppTokenToUser() {
	local url="$1"
	local note="$2"
	
	local readRecord=$(readRecordFromUrl "${AUTH_TOKEN}" "$url")
	local updateLink=$(getActionLinkFromDataRecord "$readRecord" "update")
 	local userNoActionLinks=$(getUserPartWithoutActionLinksFromRecord "$readRecord")
 	local userWithNewTokenNote=$(addTokenNoteToUser "$userNoActionLinks" "$note")
	local updateAnswer=$(sendDataToServer "${AUTH_TOKEN}" "${updateLink}" "${userWithNewTokenNote}")
	echo "$updateAnswer"
}

createExampleUserFromUserAddAppTokenAnswer() {
	local updateAnswer="$1"
	
	local token=$(extractTokenFromUpdateAnswer "$updateAnswer")
	local createdExampleUser=$(createExampleUser "$updateAnswer" "$token")
}

getActionLinkFromDataRecord(){
	local record="$1"
	local action="$2"
	echo $(echo "$record" | xmllint --xpath '//record/actionLinks/'"$action" - 2>/dev/null)
}

getUserPartWithoutActionLinksFromRecord(){
	local readRecord="$1"	
	local user=$(echo "$readRecord" | xmllint --xpath '//record/data/user' - 2>/dev/null)
	local userNoActionLinks=$(printf '%s\n' "$user" \
    	| xmlstarlet ed --omit-decl -d "//actionLinks" 2>/dev/null)
	echo "$userNoActionLinks"
}

removeAppTokensFromUser(){
	local user="$1"	
	local userNoAppToken=$(printf '%s\n' "$user" \
    	| xmlstarlet ed --omit-decl -d "//appTokens" 2>/dev/null)
	echo "$userNoAppToken"
}

removePasswordFromUser(){
	local user="$1"	
	local userNoPassword=$(xmlstarlet ed --omit-decl \
		-u "/user/usePassword" -v "false" \
		<<< "$user")
	echo "$userNoPassword"
}

addTokenNoteToUser(){
	local user="$1"
	local note="$2"
  
	local existingRepeatIds=$(xmlstarlet sel -t -v "//appTokens/appToken/@repeatId" -n <<< "$user")
	local repeatIdMax=$(echo "$existingRepeatIds" | awk '/^[0-9]+$/ {if($1>m)m=$1} END{print m+1}')
	local newRepeatId=${repeatIdMax:-1}
  
	local userWithAddedAppTokenNote=$(xmlstarlet ed --omit-decl \
		-s "/user[not(appTokens)]" -t elem -n appTokens -v "" \
		-s "/user/appTokens" -t elem -n appToken -v "" \
		-i "/user/appTokens/appToken[last()]" -t attr -n repeatId -v "$newRepeatId" \
		-s "/user/appTokens/appToken[last()]" -t elem -n appTokenNote -v "$note" \
		<<< "$user")
	echo $userWithAddedAppTokenNote
}

extractTokenFromUpdateAnswer(){
	local updateAnswer="$1"
	local token=$(echo "$updateAnswer" | \
		xmllint --xpath 'string(/record/data/user/appTokens/appToken[last()]/appTokenClearText)' - )
	echo "$token"
}

createExampleUser(){
	local userAnswer="$1"
	local appToken="$2"
	local userData="$(echo "$userAnswer" | xmllint --xpath '/record/data/user' - )"
	local url="${RECORD_URL}recordType/exampleUser"
	local readRecord=$(readRecordFromUrl "${AUTH_TOKEN}" "$url")
	local createLink=$(getActionLinkFromDataRecord "$readRecord" create)
	
	local userFirstname=$(echo "$userData" | xmllint --xpath 'string(/user/userFirstname)' - )
	local userLastname=$(echo "$userData" | xmllint --xpath 'string(/user/userLastname)' - )
 	local name="$userFirstname $userLastname"
	local userId=$(echo "$userData" | xmllint --xpath 'string(/user/recordInfo/id)' - )
	local text="Apptoken, $userId"
	local type="appTokenLogin"
	local loginId=$(echo "$userData" | xmllint --xpath 'string(/user/loginId)' - )
	
	local exampleUser=$(cat <<-EOF
	<exampleUser>
	  <recordInfo>
	    <validationType>
	      <linkedRecordType>validationType</linkedRecordType>
	      <linkedRecordId>exampleUser</linkedRecordId>
	    </validationType>
	    <dataDivider>
	      <linkedRecordType>system</linkedRecordType>
	      <linkedRecordId>coraData</linkedRecordId>
	    </dataDivider>
	  </recordInfo>
	  <name>${name}</name>
	  <text>${text}</text>
	  <type>${type}</type>
	  <loginId>${loginId}</loginId>
	  <apptoken>${appToken}</apptoken>
	</exampleUser>
EOF
	)
	local createAnswer=$(sendDataToServer "${AUTH_TOKEN}" "${createLink}" "${exampleUser}")
	echo "$createAnswer"
}
